# Generated by Django 5.2.17 on 2026-08-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(blank=True, default='Unknown', max_length=300)),
                ('genre', models.CharField(blank=True, default='General', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('goodreads_rating', models.FloatField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('rental_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('stock', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
